ob-web:
 build: .
 ports:
  - "8006:8006"
 volumes:
  - ~/.ssh:/root/.ssh
  - ./db:/ob-web-pack/db:rw
  - ./ob:/ob-web-pack/ob:rw
  - ./pages:/ob-web-pack/pages:rw
  - ./ob-web-pack:/ob-web-pack:rw
 command: /ob-web-pack/ob-web
 working_dir: /ob-web-pack